version: '3.4'

services:
  storedb:
    container_name: storedb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=gamestoredb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  game.ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ConnectionString=Server=storedb;Port=5432;Database=gamestoredb;User Id=admin;Password=admin1234;"
    ports:
      - "8010:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

